'use client'
import type { Metadata } from 'next'
import { ConfigProvider } from 'antd'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { ReduxProvider } from '@/store'

import '@/styles/globals.css'

export const metadata: Metadata = {
  title: '训练营',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ConfigProvider
          theme={{
            token: {},
          }}
        >
          <AntdRegistry>
            <ReduxProvider>
              {children}
            </ReduxProvider>
          </AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  )
}
